### ISSUE TITLE
protocol level tests are needed. messages must comply with the specified protocol.

### ISSUE THREAD

**Issue by ArtemIsmagilov** [Shopify/async-memcached#48]
For example, we need to check that the bytes we sent to the server exactly match the bytes we wanted to send. 
This PR corrects this error when we sent an extra space to the server, but most likely we expected without a space.
- #47 

This may not cause an error on the server, but it's not what we want to send.
[Link doc `get` command](https://github.com/memcached/memcached/blob/5609673ed29db98a377749fab469fe80777de8fd/doc/protocol.txt#L293)

**Comment by mrattle** [comment]
Fix for the extra whitespace in `get` commands has been incorporated into the codebase.  Thanks!
